version: 2.1

orbs:
  composer: itinerisltd/composer@0.3

workflows:
  test:
    jobs:
      - composer/install:
          name: style-check
          # Because of wp.org plugin SVN pre-commit hook.
          executor: composer/php-72
          post-steps:
            - composer/exec:
                command: style:check
